# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/merl/github_repos/azadi/fpga/debug/debug.cache/wt [current_project]
set_property parent.project_path /home/merl/github_repos/azadi/fpga/debug/debug.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/merl/github_repos/azadi/fpga/debug/debug.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  /home/merl/github_repos/azadi/src/dummy_memory/DFFRAM.sv
  /home/merl/github_repos/azadi/src/TileLink/rtl/tlul_pkg.sv
  /home/merl/github_repos/azadi/src/rv_dm/rtl/jtag_pkg.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_pkg.sv
  /home/merl/github_repos/azadi/src/TileLink/rtl/tl_main_pkg.sv
  /home/merl/github_repos/azadi/src/pulp_riscv_dbg/src/dm_pkg.sv
  /home/merl/github_repos/azadi/src/azadi_soc/rtl/azadi_soc_top.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_core.sv
  /home/merl/github_repos/azadi/src/azadi_soc/rtl/brq_core_top.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_counter.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_cs_registers.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_csr.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_exu.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_exu_alu.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_exu_multdiv_fast.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_exu_multdiv_slow.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_idu.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_idu_controller.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_idu_decoder.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_ifu.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_ifu_compressed_decoder.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_ifu_dummy_instr.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_ifu_fifo.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_ifu_icache.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_ifu_prefetch_buffer.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_lsu.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_pmp.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_register_file_ff.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/brq_wbu.sv
  /home/merl/github_repos/azadi/src/dummy_memory/data_mem.sv
  /home/merl/github_repos/azadi/src/pulp_riscv_dbg/debug_rom/debug_rom.sv
  /home/merl/github_repos/azadi/src/pulp_riscv_dbg/debug_rom/debug_rom_one_scratch.sv
  /home/merl/github_repos/azadi/src/pulp_riscv_dbg/src/dm_csrs.sv
  /home/merl/github_repos/azadi/src/pulp_riscv_dbg/src/dm_mem.sv
  /home/merl/github_repos/azadi/src/pulp_riscv_dbg/src/dm_sba.sv
  /home/merl/github_repos/azadi/src/pulp_riscv_dbg/src/dmi_cdc.sv
  /home/merl/github_repos/azadi/src/pulp_riscv_dbg/src/dmi_jtag.sv
  /home/merl/github_repos/azadi/src/pulp_riscv_dbg/src/dmi_jtag_tap.sv
  /home/merl/github_repos/azadi/src/TileLink/rtl/fifo_async.sv
  /home/merl/github_repos/azadi/src/TileLink/rtl/fifo_sync.sv
  /home/merl/github_repos/azadi/src/GPIO/rtl/gpio_reg_pkg.sv
  /home/merl/github_repos/azadi/src/GPIO/rtl/gpio.sv
  /home/merl/github_repos/azadi/src/GPIO/rtl/gpio_reg_top.sv
  /home/merl/github_repos/azadi/src/dummy_memory/instr_mem_top.sv
  /home/merl/github_repos/azadi/src/primitives/rtl/prim_arbiter_ppc.sv
  /home/merl/github_repos/azadi/src/brq_core/rtl/prim_pkg.sv
  /home/merl/github_repos/azadi/src/primitives/rtl/prim_clock_gating.sv
  /home/merl/github_repos/azadi/src/primitives/rtl/prim_filter_ctr.sv
  /home/merl/github_repos/azadi/src/primitives/rtl/prim_generic_clock_gating.sv
  /home/merl/github_repos/azadi/src/primitives/rtl/prim_generic_clock_inv.sv
  /home/merl/github_repos/azadi/src/primitives/rtl/prim_generic_clock_mux2.sv
  /home/merl/github_repos/azadi/src/primitives/rtl/prim_generic_flop.sv
  /home/merl/github_repos/azadi/src/primitives/rtl/prim_generic_flop_2sync.sv
  /home/merl/github_repos/azadi/src/primitives/rtl/prim_intr_hw.sv
  /home/merl/github_repos/azadi/src/primitives/rtl/prim_subreg.sv
  /home/merl/github_repos/azadi/src/primitives/rtl/prim_subreg_arb.sv
  /home/merl/github_repos/azadi/src/primitives/rtl/prim_subreg_ext.sv
  /home/merl/github_repos/azadi/src/azadi_soc/rtl/rstmgr.sv
  /home/merl/github_repos/azadi/src/rv_dm/rtl/rv_dm.sv
  /home/merl/github_repos/azadi/src/rv_plic/rtl/rv_plic_reg_pkg.sv
  /home/merl/github_repos/azadi/src/rv_plic/rtl/rv_plic.sv
  /home/merl/github_repos/azadi/src/rv_plic/rtl/rv_plic_gateway.sv
  /home/merl/github_repos/azadi/src/rv_plic/rtl/rv_plic_reg_top.sv
  /home/merl/github_repos/azadi/src/rv_plic/rtl/rv_plic_target.sv
  /home/merl/github_repos/azadi/src/TileLink/rtl/tl_periph_pkg.sv
  /home/merl/github_repos/azadi/src/TileLink/rtl/tl_xbar_main.sv
  /home/merl/github_repos/azadi/src/TileLink/rtl/tlul_adapter_reg.sv
  /home/merl/github_repos/azadi/src/TileLink/rtl/tlul_err.sv
  /home/merl/github_repos/azadi/src/TileLink/rtl/tlul_err_resp.sv
  /home/merl/github_repos/azadi/src/TileLink/rtl/tlul_fifo_sync.sv
  /home/merl/github_repos/azadi/src/TileLink/rtl/tlul_host_adapter.sv
  /home/merl/github_repos/azadi/src/TileLink/rtl/tlul_socket_1n.sv
  /home/merl/github_repos/azadi/src/TileLink/rtl/tlul_socket_m1.sv
  /home/merl/github_repos/azadi/src/TileLink/rtl/tlul_sram_adapter.sv
  /home/merl/github_repos/azadi/src/TileLink/rtl/xbar_periph.sv
  /home/merl/github_repos/azadi/src/azadi_soc/rtl/azadi_top_arty7.sv
}
read_verilog -library xil_defaultlib {
  /home/merl/github_repos/azadi/src/azadi_soc/rtl/iccm_controller.v
  /home/merl/github_repos/azadi/src/azadi_soc/rtl/uart_rx.v
}
read_ip -quiet /home/merl/github_repos/azadi/fpga/debug/debug.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/merl/github_repos/azadi/fpga/debug/debug.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/merl/github_repos/azadi/fpga/debug/debug.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/merl/github_repos/azadi/fpga/debug/debug.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/merl/github_repos/azadi/fpga/debug/debug.srcs/constrs_1/new/debug.xdc
set_property used_in_implementation false [get_files /home/merl/github_repos/azadi/fpga/debug/debug.srcs/constrs_1/new/debug.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top azadi_top_arty7 -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef azadi_top_arty7.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file azadi_top_arty7_utilization_synth.rpt -pb azadi_top_arty7_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
